name: myfin
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: any
  firebase_auth: any
  intl: ^0.20.2
  flutter_bloc: ^9.1.0
  google_generative_ai: ^0.4.0  
  flutter_dotenv: ^6.0.0  
  flutter_markdown_plus: ^1.0.5
  equatable: ^2.0.7
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.1.2
  uuid: ^4.5.2
  cloud_firestore: ^6.1.0
  convex_bottom_bar: 3.2.0
  file_picker: ^10.3.7
  image_picker: ^1.2.1
  pdf: ^3.10.8
  path_provider: ^2.1.5
  share_plus: ^12.0.1
  printing: ^5.12.0
  shared_preferences: ^2.5.4
  intl_phone_field: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/MyFin.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/MyFin.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/MyFin.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/MyFin.png"

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/